site_name: hhhhala
site_url: http://example.com/

nav:
  - 前端:
    - Nodejs:

  - 其他: 
      - Django: 
        - 项目文件夹文件说明: other/Django/file-description.md
        - django-settings.py配置介绍: other/Django/django-settings.py.md
        - django搭建: other/Django/django-build.md
        - django orm 中创建关系表: other/Django/django-orm.md
        - django路由层: other/Django/django-router.md
        - django视图层: other/Django/django-view.md
        - django模板层: other/Django/django-models.md
        - django数据库的配置: other/Django/django-sqlos.md
        - django数据库的操作: other/Django/django-sql.md
  - 项目:
      - 通用后台管理系统:
        - Project/index.md
theme: 
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/hhhhala/hhhhala.github.io/ # 右上角点击跳转的链接
repo_name: hhhhala.github.i # 右上角的名字
## [bottom-left corner]
copyright: hhhhala TS-1.0 # 左下角的版权声明
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/312701905
      name: Bilibili | hhhhala- # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/hhhhala
      name: GitHub | hhhhala
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
